void initShip(ship* shipList);
double distance(coordinate* positionX, coordinate* positionY);
void moveToPort(char type, lot* lots, int idGood, ship* ship);
int findPorts(ship* shipList);
int findRequestPort(int idGood, lot* lots, ship* shipList); 
void loadLot(lot* lots, int idGood, ship* shipList);
void unloadLot(lot* lots, ship* shipList);
void decreaseSem (struct sembuf sops, int sem_id, int sem_num);
void increaseSem (struct sembuf sops, int sem_id, int sem_num);
void waitForZero (struct sembuf sops, int sem_id, int sem_num);
